# coding: utf-8

"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import meli
from meli.api.items_api import ItemsApi  # noqa: E501
from meli.rest import ApiException


class TestItemsApi(unittest.TestCase):
    """ItemsApi unit test stubs"""

    def setUp(self):
        self.api = meli.api.items_api.ItemsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_items_id_get(self):
        """Test case for items_id_get

        Return a Item.  # noqa: E501
        """
        pass

    def test_items_id_put(self):
        """Test case for items_id_put

        Update a Item.  # noqa: E501
        """
        pass

    def test_items_post(self):
        """Test case for items_post

        Create a Item.  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
