# coding: utf-8

"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import meli
from meli.api.rest_client_api import RestClientApi  # noqa: E501
from meli.rest import ApiException


class TestRestClientApi(unittest.TestCase):
    """RestClientApi unit test stubs"""

    def setUp(self):
        self.api = meli.api.rest_client_api.RestClientApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_resource_delete(self):
        """Test case for resource_delete

        Resource path DELETE  # noqa: E501
        """
        pass

    def test_resource_get(self):
        """Test case for resource_get

        Resource path GET  # noqa: E501
        """
        pass

    def test_resource_post(self):
        """Test case for resource_post

        Resourse path POST  # noqa: E501
        """
        pass

    def test_resource_put(self):
        """Test case for resource_put

        Resourse path PUT  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
