# coding: utf-8

"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import meli
from meli.models.variations_attribute_combinations import VariationsAttributeCombinations  # noqa: E501
from meli.rest import ApiException

class TestVariationsAttributeCombinations(unittest.TestCase):
    """VariationsAttributeCombinations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test VariationsAttributeCombinations
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = meli.models.variations_attribute_combinations.VariationsAttributeCombinations()  # noqa: E501
        if include_optional :
            return VariationsAttributeCombinations(
                name = 'Color', 
                value_id = '283165', 
                value_name = 'Gris'
            )
        else :
            return VariationsAttributeCombinations(
        )

    def testVariationsAttributeCombinations(self):
        """Test VariationsAttributeCombinations"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
