# coding: utf-8

"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import meli
from meli.models.variations import Variations  # noqa: E501
from meli.rest import ApiException

class TestVariations(unittest.TestCase):
    """Variations unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Variations
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = meli.models.variations.Variations()  # noqa: E501
        if include_optional :
            return Variations(
                price = 350, 
                attribute_combinations = [
                    meli.models.variations_attribute_combinations.Variations_attribute_combinations(
                        name = 'Color', 
                        value_id = '283165', 
                        value_name = 'Gris', )
                    ], 
                available_quantity = 2, 
                sold_quantity = 0, 
                picture_ids = [
                    '882629-MLA40983876214_032020'
                    ]
            )
        else :
            return Variations(
        )

    def testVariations(self):
        """Test Variations"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
