# coding: utf-8

"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import meli
from meli.models.item_pictures import ItemPictures  # noqa: E501
from meli.rest import ApiException

class TestItemPictures(unittest.TestCase):
    """ItemPictures unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test ItemPictures
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = meli.models.item_pictures.ItemPictures()  # noqa: E501
        if include_optional :
            return ItemPictures(
                source = 'https://http2.mlstatic.com/storage/developers-site-cms-admin/openapi/319968615067-mp3.jpg'
            )
        else :
            return ItemPictures(
        )

    def testItemPictures(self):
        """Test ItemPictures"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
