# coding: utf-8

"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import meli
from meli.api.o_auth_2_0_api import OAuth20Api  # noqa: E501
from meli.rest import ApiException


class TestOAuth20Api(unittest.TestCase):
    """OAuth20Api unit test stubs"""

    def setUp(self):
        self.api = meli.api.o_auth_2_0_api.OAuth20Api()  # noqa: E501

    def tearDown(self):
        pass

    def test_auth(self):
        """Test case for auth

        Authentication Endpoint  # noqa: E501
        """
        pass

    def test_get_token(self):
        """Test case for get_token

        Request Access Token  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
