# coding: utf-8

"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import meli
from meli.models.item import Item  # noqa: E501
from meli.rest import ApiException

class TestItem(unittest.TestCase):
    """Item unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test Item
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = meli.models.item.Item()  # noqa: E501
        if include_optional :
            return Item(
                title = 'Item de test - No Ofertar', 
                category_id = 'MLA5991', 
                price = 350, 
                currency_id = 'ARS', 
                available_quantity = '12', 
                buying_mode = 'buy_it_now', 
                listing_type_id = 'bronze', 
                condition = 'new', 
                description = 'Item de Teste. Mercado Livre SDK', 
                video_id = 'RXWn6kftTHY', 
                pictures = [
                    meli.models.item_pictures.Item_pictures(
                        source = 'https://http2.mlstatic.com/storage/developers-site-cms-admin/openapi/319968615067-mp3.jpg', )
                    ], 
                attributes = [
                    meli.models.attributes.Attributes(
                        id = 'DATA_STORAGE_CAPACITY', 
                        name = 'Capacidad de almacenamiento de datos', 
                        value_id = '0', 
                        value_name = '8 GB', 
                        value_struct = meli.models.attributes_value_struct.Attributes_value_struct(
                            number = 8, 
                            unit = 'GB', ), 
                        values = [
                            meli.models.attributes_values.Attributes_values(
                                id = '0', 
                                name = '8 GB', 
                                struct = meli.models.attributes_value_struct.Attributes_value_struct(
                                    number = 8, 
                                    unit = 'GB', ), )
                            ], 
                        attribute_group_id = 'OTHERS', 
                        attribute_group_name = 'Otros', )
                    ], 
                variations = [
                    meli.models.variations.Variations(
                        price = 350, 
                        attribute_combinations = [
                            meli.models.variations_attribute_combinations.Variations_attribute_combinations(
                                name = 'Color', 
                                value_id = '283165', 
                                value_name = 'Gris', )
                            ], 
                        available_quantity = 2, 
                        sold_quantity = 0, 
                        picture_ids = [
                            '882629-MLA40983876214_032020'
                            ], )
                    ]
            )
        else :
            return Item(
                title = 'Item de test - No Ofertar',
                category_id = 'MLA5991',
                price = 350,
                currency_id = 'ARS',
                available_quantity = '12',
                buying_mode = 'buy_it_now',
                listing_type_id = 'bronze',
                condition = 'new',
                description = 'Item de Teste. Mercado Livre SDK',
                video_id = 'RXWn6kftTHY',
                pictures = [
                    meli.models.item_pictures.Item_pictures(
                        source = 'https://http2.mlstatic.com/storage/developers-site-cms-admin/openapi/319968615067-mp3.jpg', )
                    ],
        )

    def testItem(self):
        """Test Item"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
