# coding: utf-8

# flake8: noqa
"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

# import models into model package
from meli.models.attributes import Attributes
from meli.models.attributes_value_struct import AttributesValueStruct
from meli.models.attributes_values import AttributesValues
from meli.models.inline_object import InlineObject
from meli.models.item import Item
from meli.models.item_pictures import ItemPictures
from meli.models.variations import Variations
from meli.models.variations_attribute_combinations import VariationsAttributeCombinations
