# coding: utf-8

"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from meli.configuration import Configuration


class AttributesValues(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'id': 'str',
        'name': 'str',
        'struct': 'AttributesValueStruct'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'struct': 'struct'
    }

    def __init__(self, id=None, name=None, struct=None, local_vars_configuration=None):  # noqa: E501
        """AttributesValues - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._id = None
        self._name = None
        self._struct = None
        self.discriminator = None

        self.id = id
        if name is not None:
            self.name = name
        self.struct = struct

    @property
    def id(self):
        """Gets the id of this AttributesValues.  # noqa: E501


        :return: The id of this AttributesValues.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AttributesValues.


        :param id: The id of this AttributesValues.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AttributesValues.  # noqa: E501


        :return: The name of this AttributesValues.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AttributesValues.


        :param name: The name of this AttributesValues.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def struct(self):
        """Gets the struct of this AttributesValues.  # noqa: E501


        :return: The struct of this AttributesValues.  # noqa: E501
        :rtype: AttributesValueStruct
        """
        return self._struct

    @struct.setter
    def struct(self, struct):
        """Sets the struct of this AttributesValues.


        :param struct: The struct of this AttributesValues.  # noqa: E501
        :type: AttributesValueStruct
        """

        self._struct = struct

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AttributesValues):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AttributesValues):
            return True

        return self.to_dict() != other.to_dict()
