# coding: utf-8

"""
    MELI Markeplace SDK

    This is a the codebase to generate a SDK for Open Platform Marketplace  # noqa: E501

    The version of the OpenAPI document: 3.0.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from meli.configuration import Configuration


class InlineObject(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'grant_type': 'str',
        'client_id': 'str',
        'client_secret': 'str',
        'redirect_uri': 'str',
        'code': 'str',
        'refresh_token': 'str'
    }

    attribute_map = {
        'grant_type': 'grant_type',
        'client_id': 'client_id',
        'client_secret': 'client_secret',
        'redirect_uri': 'redirect_uri',
        'code': 'code',
        'refresh_token': 'refresh_token'
    }

    def __init__(self, grant_type=None, client_id=None, client_secret=None, redirect_uri=None, code=None, refresh_token=None, local_vars_configuration=None):  # noqa: E501
        """InlineObject - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._grant_type = None
        self._client_id = None
        self._client_secret = None
        self._redirect_uri = None
        self._code = None
        self._refresh_token = None
        self.discriminator = None

        if grant_type is not None:
            self.grant_type = grant_type
        if client_id is not None:
            self.client_id = client_id
        if client_secret is not None:
            self.client_secret = client_secret
        if redirect_uri is not None:
            self.redirect_uri = redirect_uri
        if code is not None:
            self.code = code
        if refresh_token is not None:
            self.refresh_token = refresh_token

    @property
    def grant_type(self):
        """Gets the grant_type of this InlineObject.  # noqa: E501


        :return: The grant_type of this InlineObject.  # noqa: E501
        :rtype: str
        """
        return self._grant_type

    @grant_type.setter
    def grant_type(self, grant_type):
        """Sets the grant_type of this InlineObject.


        :param grant_type: The grant_type of this InlineObject.  # noqa: E501
        :type: str
        """

        self._grant_type = grant_type

    @property
    def client_id(self):
        """Gets the client_id of this InlineObject.  # noqa: E501


        :return: The client_id of this InlineObject.  # noqa: E501
        :rtype: str
        """
        return self._client_id

    @client_id.setter
    def client_id(self, client_id):
        """Sets the client_id of this InlineObject.


        :param client_id: The client_id of this InlineObject.  # noqa: E501
        :type: str
        """

        self._client_id = client_id

    @property
    def client_secret(self):
        """Gets the client_secret of this InlineObject.  # noqa: E501


        :return: The client_secret of this InlineObject.  # noqa: E501
        :rtype: str
        """
        return self._client_secret

    @client_secret.setter
    def client_secret(self, client_secret):
        """Sets the client_secret of this InlineObject.


        :param client_secret: The client_secret of this InlineObject.  # noqa: E501
        :type: str
        """

        self._client_secret = client_secret

    @property
    def redirect_uri(self):
        """Gets the redirect_uri of this InlineObject.  # noqa: E501


        :return: The redirect_uri of this InlineObject.  # noqa: E501
        :rtype: str
        """
        return self._redirect_uri

    @redirect_uri.setter
    def redirect_uri(self, redirect_uri):
        """Sets the redirect_uri of this InlineObject.


        :param redirect_uri: The redirect_uri of this InlineObject.  # noqa: E501
        :type: str
        """

        self._redirect_uri = redirect_uri

    @property
    def code(self):
        """Gets the code of this InlineObject.  # noqa: E501


        :return: The code of this InlineObject.  # noqa: E501
        :rtype: str
        """
        return self._code

    @code.setter
    def code(self, code):
        """Sets the code of this InlineObject.


        :param code: The code of this InlineObject.  # noqa: E501
        :type: str
        """

        self._code = code

    @property
    def refresh_token(self):
        """Gets the refresh_token of this InlineObject.  # noqa: E501


        :return: The refresh_token of this InlineObject.  # noqa: E501
        :rtype: str
        """
        return self._refresh_token

    @refresh_token.setter
    def refresh_token(self, refresh_token):
        """Sets the refresh_token of this InlineObject.


        :param refresh_token: The refresh_token of this InlineObject.  # noqa: E501
        :type: str
        """

        self._refresh_token = refresh_token

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InlineObject):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InlineObject):
            return True

        return self.to_dict() != other.to_dict()
